DATASET:
  NAME: 'PREPROCESSED_SAR_MSI'
  ROOT: 'E:/zts/dataset/SAR_MSI_preprocessed_15000_average_all'
  FUSION: 'concat'
  CLASSES_INTEREST:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16

DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 0

MODEL:
  NAME: 'resnet101'

CRITERION:
  NAME: 'softmax+ce'

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 40
