DATASET:
  NAME: 'RAW_SAR_MSI'
  ROOT: 'E:/dataset/SAR-MSI_dataset/So2Sat_LCZ42'
  DATA1:
    MEANS:
      - 0
      - 0
      - 0
      - 0
      - 0.0432
      - 0.2539
      - 0
      - 0
    STDS:
      - 0.1718
      - 0.1715
      - 0.4588
      - 0.4644
      - 0.6123
      - 10.4905
      - 1.2942
      - 0.6086
  DATA2:
    MEANS:
      - 0.1237
      - 0.1093
      - 0.1012
      - 0.1145
      - 0.1598
      - 0.1822
      - 0.1753
      - 0.1959
      - 0.1548
      - 0.1093
    STDS:
      - 0.0402
      - 0.0483
      - 0.0671
      - 0.0641
      - 0.0775
      - 0.0909
      - 0.0918
      - 0.1078
      - 0.1007
      - 0.0887
  SAMPLE_NUM:
    - 2000
    - 400
    - 600
  SAMPLE_ORDER: 'average'
  CLASSES_INTEREST:
    - 0
    - 6
    - 7
    - 10
    - 15
    - 16