DATASET:
    NAME: 'SAR_MSI'
    ROOT: 'E:/dataset/SAR-MSI_dataset/So2Sat_LCZ42'
    MEANS: # TODO: measure mean
        - 0.5
        - 0.5
        - 0.5
        - 0.5
    STDS: # TODO: measure std
        - 1
        - 1
        - 1
        - 1