DATASET:
    NAME: 'RAW_VNR_MSI'
    ROOT: 'E:/zzy/173/data/vnr-gf'
    DATA1:
        MEANS:
            - 77.299
            - 58.334
            - 54.818
        STDS:
            - 16.752
            - 17.610
            - 13.568
    DATA2:
        MEANS:
            - 446.837
            - 300.937
            - 217.913
            - 352.124
        STDS:
            - 169.302
            - 124.585
            - 125.862
            - 146.663