DATASET:
    NAME: 'RAW_SAR_MSI'
    ROOT: 'E:/dataset/SAR-MSI_dataset/So2Sat_LCZ42'
    FUSION: 'concat'

DATALOADER:
    BATCH_SIZE: 8
    NUM_WORKERS: 8

MODEL:
    NAME: 'resnet'

CRITERION:
    NAME: 'softmax+ce'

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 40
