DATASET:
    NAME: 'PREPROCESSED_SAR_MSI'
    ROOT: 'E:/zts/dataset/SAR_MSI_preprocessed'
    FUSION: 'concat'
    CLASSES_INTEREST:
        - 0
        - 9
        - 10
        - 13
        - 14
        - 16

DATALOADER:
    BATCH_SIZE: 32
    NUM_WORKERS: 8

MODEL:
    NAME: 'resnet18'

CRITERION:
    NAME: 'softmax+ce'

OPTIMIZER:
    NAME: 'adam'
    LR: 0.001

SCHEDULER:
    NAME: 'plateau'
    MODE: 'min'
    FACTOR: 0.1
    PATIENCE: 2

EPOCHS: 40
